name: Frontend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Cache Node.js
        uses: actions/cache@v3
        with:
          path: starter/frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        
      - name: Dependencies and Lint and Test
        run: | 
          cd starter/frontend
          npm ci
          npm run lint
          npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build and Tag Docker Image
        run: |
          cd starter/frontend
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://a6da210a72f424c628ae96d936ae3805-1258443996.us-east-1.elb.amazonaws.com -t ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }} .

      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Deploy K8s
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=${{ steps.login-ecr.outputs.registry }}/frontend:${{ github.sha }}
          kustomize build | kubectl apply -f -